### ISSUE TITLE
Exception on /generateSegment [GET]

### ISSUE THREAD

**Issue by wadefagen** [cs240-illinois/sp22_cs240_infinite-maze-shared#18]
```
[2022-05-01 17:23:58,541] ERROR in app: Exception on /generateSegment [GET]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\wadef\Desktop\cs240\sp22_cs240_infinite-maze-shared\app.py", line 41, in gen_rand_maze_segment
    col = int(request.args['col'])
ValueError: invalid literal for int() with base 10: '3.2857142857142856'
```

**Comment by PeterYR** [comment]
This seems to happen when using a non-central exit (#13), where the front-end calculates the coordinates to put in the URL and ends up with floating-point numbers.

I tried rounding them to integers in the middleware, which prevents the exception but leads to more weird behavior on the front-end. The front-end seems to place the newly received unit as if the exit *was* a central one, which misaligns it with the overall grid. The new maze unit seems to be invisible, too:

![image](https://cdn.discordapp.com/attachments/967277893870817290/970417582744174632/unknown.png)
